import type { ChatStudyMessage } from "@/lib/generated-chat-study";
import { inferStudySubject } from "@/lib/generated-chat-study";
import type { QuizQuestion, QuizSubject } from "@/data/quiz-bank";

export type ChatQuizMessage = ChatStudyMessage;

export type GeneratedQuizSession = {
  id: string;
  title: string;
  description: string;
  sourcePath: string;
  sourceTitle: string;
  subject: QuizSubject;
  questions: QuizQuestion[];
  createdAt: string;
};

type CreateGeneratedQuizSessionInput = {
  title: string;
  sourcePath: string;
  sourceTitle: string;
  messages: ChatQuizMessage[];
};

// ── Collect all text content from attachments in the conversation ──────────
function collectAttachmentContent(messages: ChatQuizMessage[]): string {
  const parts: string[] = [];

  for (const message of messages) {
    for (const attachment of message.attachments ?? []) {
      if (attachment.content) {
        parts.push(`[${attachment.name}]\n${attachment.content}`);
      } else {
        for (const chunk of attachment.chunks ?? []) {
          parts.push(chunk.content);
        }
      }
    }
    for (const citation of message.citations ?? []) {
      parts.push(citation.snippet);
    }
  }

  return parts.join("\n\n").trim();
}

// ── Detect Thai in content ─────────────────────────────────────────────────
function hasThaiText(text: string) {
  return /[\u0E00-\u0E7F]/.test(text);
}

// ── Call the server-side Gemini quiz generation API ────────────────────────
type RawQuestion = {
  prompt: string;
  options: string[];
  correctIndex: number;
  explanation: string;
};

async function callGenerateQuizApi(
  content: string,
  preferThai: boolean,
): Promise<RawQuestion[] | null> {
  try {
    const response = await fetch("/api/generate-quiz", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ content, preferThai }),
    });

    if (!response.ok) {
      const payload = (await response.json()) as { error?: string };
      console.error("generate-quiz API error:", payload.error);
      return null;
    }

    const payload = (await response.json()) as { questions?: RawQuestion[] };
    return payload.questions ?? null;
  } catch (error) {
    console.error("generate-quiz fetch failed:", error);
    return null;
  }
}

// ── Convert raw Gemini questions to QuizQuestion format ────────────────────
function toQuizQuestions(
  sessionId: string,
  subject: QuizSubject,
  rawQuestions: RawQuestion[],
): QuizQuestion[] {
  return rawQuestions.map((raw, index) => ({
    id: `${sessionId}-q${index + 1}`,
    subject,
    topic: "File review",
    concept: "Key ideas from the uploaded materials",
    prompt: raw.prompt,
    options: raw.options,
    correctIndex: raw.correctIndex,
    explanation: raw.explanation,
  }));
}

// ── Main export: now async ─────────────────────────────────────────────────
export async function createGeneratedQuizSession(
  input: CreateGeneratedQuizSessionInput,
): Promise<
  | { ok: true; session: GeneratedQuizSession }
  | { ok: false; message: string }
> {
  const hasAttachments = input.messages.some(
    (m) => (m.attachments ?? []).length > 0,
  );

  if (!hasAttachments) {
    return {
      ok: false,
      message:
        "อัปโหลดไฟล์เรียนในแชทก่อน แล้วกด \"Quiz from this chat\" เพื่อให้ควิซมาจากเนื้อหาไฟล์ครับ",
    };
  }

  const content = collectAttachmentContent(input.messages);

  if (content.length < 50) {
    return {
      ok: false,
      message:
        "ไม่พบเนื้อหาที่ชัดเจนในไฟล์ที่อัปโหลด ลองอัปโหลดไฟล์ที่มีข้อความมากขึ้น แล้วกด Quiz อีกครั้งครับ",
    };
  }

  const preferThai = hasThaiText(content);
  const rawQuestions = await callGenerateQuizApi(content, preferThai);

  if (!rawQuestions || rawQuestions.length === 0) {
    return {
      ok: false,
      message:
        "ไม่สามารถสร้างควิซจากไฟล์นี้ได้ในขณะนี้ ลองอีกครั้งหรืออัปโหลดไฟล์ที่มีเนื้อหาละเอียดกว่าครับ",
    };
  }

  const subject = inferStudySubject([content]);
  const sessionId = `chat-quiz-${Date.now()}`;
  const questions = toQuizQuestions(sessionId, subject, rawQuestions);

  const session: GeneratedQuizSession = {
    id: sessionId,
    title: input.title,
    description: preferThai
      ? "ควิซนี้สร้างจากการสรุปเนื้อหาไฟล์ที่อัปโหลด โดย Gemini AI"
      : "This quiz was generated by Gemini AI from a summary of your uploaded file content.",
    sourcePath: input.sourcePath,
    sourceTitle: input.sourceTitle,
    subject,
    questions,
    createdAt: new Date().toISOString(),
  };

  return { ok: true, session };
}
